/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class CursorH2NativeStream {
  write(data: Buffer, timeoutMs?: number | null | undefined): Promise<void>
  finishInput(): Promise<void>
  nextFrame(): Promise<Buffer | null>
  cancel(): Promise<void>
}

export declare function cursorH2CancelOperation(operationId: string): Promise<void>

export declare function cursorH2OpenStream(configJson: string, initialBody?: Buffer | undefined | null): Promise<CursorH2NativeStream>

export declare function cursorH2RequestUnary(configJson: string, body: Buffer): Promise<CursorH2UnaryResponse>

export interface CursorH2UnaryResponse {
  statusCode?: number
  headersJson: string
  body: Buffer
}
