import { describe, test } from "bun:test";
import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";

interface VersionedPackageJson {
  name: string;
  version: string;
  private?: boolean;
  dependencies?: Record<string, string>;
}

interface BumpResult {
  exitCode: number | null;
  stdout: string;
  stderr: string;
}

function writeJson(path: string, value: VersionedPackageJson): void {
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`);
}

function readJson(path: string): VersionedPackageJson {
  return JSON.parse(readFileSync(path, "utf8")) as VersionedPackageJson;
}

function createFixtureRoot(): string {
  const root = mkdtempSync(join(tmpdir(), "atomic-bump-version-"));
  mkdirSync(join(root, "packages", "alpha"), { recursive: true });
  mkdirSync(join(root, "packages", "beta"), { recursive: true });
  mkdirSync(join(root, "packages", "natives", "native"), { recursive: true });
  mkdirSync(join(root, "crates", "native"), { recursive: true });

  writeJson(join(root, "package.json"), {
    name: "fixture-monorepo",
    version: "0.1.0",
    private: true,
    dependencies: {
      "@bastani/atomic-natives": "0.1.0",
    },
  });
  writeFileSync(
    join(root, "Cargo.toml"),
    '[workspace]\nmembers = ["crates/native"]\n\n[workspace.package]\nversion = "0.1.0"\nedition = "2024"\n',
  );
  writeFileSync(
    join(root, "Cargo.lock"),
    '# This file is automatically @generated by Cargo.\n\n[[package]]\nname = "atomic-native"\nversion = "0.1.0"\n\n[[package]]\nname = "atomic-waker"\nversion = "1.1.2"\nsource = "registry+https://github.com/rust-lang/crates.io-index"\nchecksum = "fixture-checksum"\n\n[[package]]\nname = "third-party"\nversion = "9.9.9"\n',
  );
  writeJson(join(root, "packages", "alpha", "package.json"), {
    name: "@fixture/alpha",
    version: "0.1.0",
    private: true,
  });
  writeJson(join(root, "packages", "beta", "package.json"), {
    name: "@fixture/beta",
    version: "0.1.0",
    private: true,
  });
  writeFileSync(
    join(root, "packages", "alpha", "README.md"),
    '<img src="https://img.shields.io/badge/version-0.1.0-blue" alt="Version 0.1.0">\n',
  );
  writeFileSync(
    join(root, "crates", "native", "Cargo.toml"),
    '[package]\nname = "atomic-native"\nversion = "0.1.0"\nedition = "2024"\n',
  );
  writeFileSync(
    join(root, "packages", "natives", "native", "index.js"),
    `/* auto-generated by NAPI-RS */
if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK) {
  throw new Error(\`Native binding package version mismatch, expected 0.1.0 but got \${bindingPackageVersion}\`)
}
if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK) {
  throw new Error(\`Native binding package version mismatch, expected 0.1.0 but got \${bindingPackageVersion}\`)
}
`,
  );

  return root;
}

function runBump(root: string, version: string): BumpResult {
  const result = Bun.spawnSync({
    cmd: [process.execPath, "run", join(process.cwd(), "scripts", "bump-version.ts"), version, "--root", root],
    stdout: "pipe",
    stderr: "pipe",
  });

  return {
    exitCode: result.exitCode,
    stdout: result.stdout.toString(),
    stderr: result.stderr.toString(),
  };
}

describe("scripts/bump-version.ts", () => {
  test("updates every versioned package manifest and README badge", () => {
    const root = createFixtureRoot();
    try {
      const result = runBump(root, "1.2.3-alpha.1");
      assert.equal(result.exitCode, 0, result.stderr);

      const rootPackageJson = readJson(join(root, "package.json"));
      assert.equal(rootPackageJson.version, "1.2.3-alpha.1");
      assert.equal(rootPackageJson.dependencies?.["@bastani/atomic-natives"], "1.2.3-alpha.1");
      assert.equal(readJson(join(root, "packages", "alpha", "package.json")).version, "1.2.3-alpha.1");
      assert.equal(readJson(join(root, "packages", "beta", "package.json")).version, "1.2.3-alpha.1");
      assert.match(readFileSync(join(root, "Cargo.toml"), "utf8"), /version = "1\.2\.3-alpha\.1"/);
      assert.match(readFileSync(join(root, "crates", "native", "Cargo.toml"), "utf8"), /version = "1\.2\.3-alpha\.1"/);
      const cargoLock = readFileSync(join(root, "Cargo.lock"), "utf8");
      assert.match(cargoLock, /name = "atomic-native"\nversion = "1\.2\.3-alpha\.1"/);
      assert.match(cargoLock, /name = "atomic-waker"\nversion = "1\.1\.2"/);
      assert.match(cargoLock, /name = "third-party"\nversion = "9\.9\.9"/);
      assert.match(
        readFileSync(join(root, "packages", "alpha", "README.md"), "utf8"),
        /version-1\.2\.3--alpha\.1-blue" alt="Version 1\.2\.3-alpha\.1"/,
      );
      const nativeIndex = readFileSync(join(root, "packages", "natives", "native", "index.js"), "utf8");
      assert.match(nativeIndex, /bindingPackageVersion !== '1\.2\.3-alpha\.1'/);
      assert.match(nativeIndex, /expected 1\.2\.3-alpha\.1 but got \$\{bindingPackageVersion\}/);
      assert.doesNotMatch(nativeIndex, /0\.1\.0/);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("rejects v-prefixed, legacy-numeric, and malformed alpha prerelease versions", () => {
    // The prerelease convention is `-alpha.N` with the revision starting at 1.
    // Legacy numeric prereleases (the old `-0`/`-4` style suffix) and any other
    // suffix shape are rejected.
    const invalidVersions = [
      "v1.2.3",
      "1.2.3-0",
      "1.2.3-alpha.0",
      "1.2.3-alpha",
      "1.2.3-alpha.01",
      "1.2.3-rc.1",
      "01.2.3",
    ];

    for (const version of invalidVersions) {
      const root = createFixtureRoot();
      try {
        const result = runBump(root, version);
        assert.notEqual(result.exitCode, 0, `${version} should be rejected`);
        assert.match(result.stderr, /Expected MAJOR\.MINOR\.PATCH or MAJOR\.MINOR\.PATCH-alpha\.REVISION/);
        assert.equal(readJson(join(root, "package.json")).version, "0.1.0");
        assert.equal(readJson(join(root, "packages", "alpha", "package.json")).version, "0.1.0");
      } finally {
        rmSync(root, { recursive: true, force: true });
      }
    }
  });
});
